application: road-719
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: host.application
# Endpoints handler
- url: /_ah/spi/.*
  script: helloworld_api.APPLICATION

libraries:
- name: webapp2
  version: latest

- name: MySQLdb
  version: "latest"

- name: jinja2
  version: "latest"

- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0


